# Generated by Django 2.2.16 on 2021-04-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixture_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.TextField(default='n/a')),
                ('team2', models.TextField(default='123')),
                ('deadline', models.TextField(default='123')),
            ],
        ),
    ]
