# Generated by Django 2.2.16 on 2021-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_fixture_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture_model',
            name='match_no',
            field=models.TextField(default='n/a'),
        ),
    ]
