# Generated by Django 2.2.16 on 2021-04-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_prediction_model_match_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='points',
            field=models.TextField(default='0'),
        ),
    ]
