# Generated by Django 2.2.16 on 2021-04-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_login_model_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture_model',
            name='winner_predict',
            field=models.TextField(default='false'),
        ),
    ]
