# Generated by Django 2.2.16 on 2021-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_fixture_model_winner_predict'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='rank',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='fixture_model',
            name='winner_predict',
            field=models.TextField(default='f'),
        ),
    ]
